### PR TITLE
add short version and fix opacity bug

### PR DESCRIPTION
**Pull request by JOYBOY-0**
- Make assets shorter on mobile
- Fix opacity bug on resize

### CODE REVIEW

**Comment by jasonLaster** [comment]
The assets should be below the description.

Screenshot 2023-06-09 at 1 32 04 PM

**Comment by JOYBOY-0** [comment]
> The assets should be below the description.
> 
> Screenshot 2023-06-09 at 1 32 04 PM

Im on it! Everything else looking good?

**Comment by JOYBOY-0** [comment]
@jasonLaster take a look to the latest changes when you can, please 🙌

**Comment by jasonLaster** [comment]
Nailed it

**Review by matiasperz — APPROVED** [review]

**Pull request merged**
